apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: webhook
  name: configmap-reader
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-reader-binding
  namespace: webhook
subjects:
- kind: ServiceAccount
  name: default
  namespace: webhook
roleRef:
  kind: Role
  name: configmap-reader
  apiGroup: rbac.authorization.k8s.io
